const cloudflareColoNames: Record<string, string> = {
  "AAE": "Annaba, Algeria",
  "ABJ": "Abidjan, Ivory Coast",
  "ABQ": "Albuquerque, NM, United States",
  "ACC": "Accra, Ghana",
  "ACX": "Xingyi, China",
  "ADB": "Izmir, Turkey",
  "ADD": "Addis Ababa, Ethiopia",
  "ADL": "Adelaide, SA, Australia",
  "AGR": "Agra, India",
  "AKL": "Auckland, New Zealand",
  "AKX": "Aktobe, Kazakhstan",
  "ALA": "Almaty, Kazakhstan",
  "ALG": "Algiers, Algeria",
  "AMD": "Ahmedabad, India",
  "AMM": "Amman, Jordan",
  "AMS": "Amsterdam, Netherlands",
  "ANC": "Anchorage, AK, United States",
  "ARI": "Arica, Chile",
  "ARN": "Stockholm, Sweden",
  "ARU": "Aracatuba, Brazil",
  "ASK": "Yamoussoukro, Ivory Coast",
  "ASU": "Asunción, Paraguay",
  "ATH": "Athens, Greece",
  "ATL": "Atlanta, GA, United States",
  "AUS": "Austin, TX, United States",
  "BAH": "Manama, Bahrain",
  "BAQ": "Barranquilla, Colombia",
  "BBI": "Bhubaneswar, India",
  "BCN": "Barcelona, Spain",
  "BEG": "Belgrade, Serbia",
  "BEL": "Belém, Brazil",
  "BEY": "Beirut, Lebanon",
  "BGI": "Bridgetown, Barbados",
  "BGR": "Bangor, ME, United States",
  "BGW": "Baghdad, Iraq",
  "BHY": "Beihai, China",
  "BKK": "Bangkok, Thailand",
  "BLR": "Bangalore, India",
  "BNA": "Nashville, United States",
  "BNE": "Brisbane, QLD, Australia",
  "BOD": "Bordeaux, France",
  "BOG": "Bogotá, Colombia",
  "BOM": "Mumbai, India",
  "BOS": "Boston, MA, United States",
  "BRU": "Brussels, Belgium",
  "BSB": "Brasilia, Brazil",
  "BSR": "Basra, Iraq",
  "BTS": "Bratislava, Slovakia  ",
  "BUD": "Budapest, Hungary",
  "BUF": "Buffalo, NY, United States",
  "BWN": "Bandar Seri Begawan, Brunei",
  "CAI": "Cairo, Egypt",
  "CAN": "Guangzhou, China",
  "CAW": "Campos dos Goytacazes, Brazil",
  "CBR": "Canberra, ACT, Australia",
  "CCU": "Kolkata, India",
  "CDG": "Paris, France",
  "CEB": "Cebu, Philippines",
  "CFC": "Caçador, Brazil",
  "CGB": "Cuiaba, Brazil",
  "CGD": "Changde, China",
  "CGK": "Jakarta, Indonesia",
  "CGO": "Zhengzhou, China",
  "CGP": "Chittagong, Bangladesh",
  "CGY": "Cagayan de Oro, Philippines",
  "CHC": "Christchurch, New Zealand",
  "CJB": "Coimbatore, India",
  "CKG": "Chongqing, China",
  "CLE": "Cleveland, OH, United States",
  "CLO": "Cali, Colombia",
  "CLT": "Charlotte, NC, United States",
  "CMB": "Colombo, Sri Lanka",
  "CMH": "Columbus, OH, United States",
  "CNF": "Belo Horizonte, Brazil",
  "CNN": "Kannur, India",
  "CNX": "Chiang Mai, Thailand",
  "COK": "Kochi, India",
  "COR": "Córdoba, Argentina",
  "CPH": "Copenhagen, Denmark",
  "CPT": "Cape Town, South Africa",
  "CRK": "Tarlac City, Philippines",
  "CSX": "Changsha, China",
  "CTU": "Chengdu, China",
  "CVG": "Cincinnati, United States",
  "CWB": "Curitiba, Brazil",
  "CZL": "Constantine, Algeria",
  "CZX": "Changzhou, China",
  "DAC": "Dhaka, Bangladesh",
  "DAD": "Da Nang, Vietnam",
  "DAR": "Dar Es Salaam, Tanzania",
  "DEL": "New Delhi, India",
  "DEN": "Denver, CO, United States",
  "DFW": "Dallas, TX, United States",
  "DKR": "Dakar, Senegal",
  "DLA": "Douala, Cameroon",
  "DLC": "Dalian, China",
  "DME": "Moscow, Russia",
  "DMM": "Dammam, Saudi Arabia",
  "DOH": "Doha, Qatar",
  "DPS": "Denpasar, Indonesia",
  "DTW": "Detroit, MI, United States",
  "DUB": "Dublin, Ireland",
  "DUR": "Durban, South Africa",
  "DUS": "Düsseldorf, Germany",
  "DXB": "Dubai, United Arab Emirates",
  "EBB": "Kampala, Uganda",
  "EBL": "Erbil, Iraq",
  "EVN": "Yerevan, Armenia",
  "EWR": "Newark, NJ, United States",
  "EZE": "Buenos Aires, Argentina",
  "FCO": "Rome, Italy",
  "FIH": "Kinshasa, DR Congo",
  "FLN": "Florianopolis, Brazil",
  "FOC": "Fuzhou, China",
  "FOR": "Fortaleza, Brazil",
  "FRA": "Frankfurt, Germany",
  "FRU": "Bishkek, Kyrgyzstan",
  "FSD": "Sioux Falls, SD, United States",
  "FUK": "Fukuoka, Japan",
  "FUO": "Foshan, China",
  "GBE": "Gaborone, Botswana",
  "GDL": "Guadalajara, Mexico",
  "GEO": "Georgetown, Guyana",
  "GIG": "Rio de Janeiro, Brazil",
  "GND": "St. George's, Grenada",
  "GOT": "Gothenburg, Sweden",
  "GRU": "São Paulo, Brazil",
  "GUA": "Guatemala City, Guatemala",
  "GUM": "Hagatna, Guam",
  "GVA": "Geneva, Switzerland",
  "GYD": "Baku, Azerbaijan",
  "GYE": "Guayaquil, Ecuador",
  "GYN": "Goiânia, Brazil",
  "HAK": "Haikou, China",
  "HAM": "Hamburg, Germany",
  "HAN": "Hanoi, Vietnam",
  "HBA": "Hobart, Australia",
  "HEL": "Helsinki, Finland",
  "HFA": "Haifa, Israel",
  "HGH": "Shaoxing, China",
  "HKG": "Hong Kong",
  "HNL": "Honolulu, HI, United States",
  "HRE": "Harare, Zimbabwe",
  "HYD": "Hyderabad, India",
  "HYN": "Taizhou, China",
  "IAD": "Ashburn, VA, United States",
  "IAH": "Houston, TX, United States",
  "ICN": "Seoul, South Korea",
  "IND": "Indianapolis, IN, United States",
  "ISB": "Islamabad, Pakistan",
  "IST": "Istanbul, Turkey",
  "ISU": "Sulaymaniyah, Iraq",
  "IXC": "Chandigarh, India",
  "JAX": "Jacksonville, FL, United States",
  "JDO": "Juazeiro do Norte, Brazil",
  "JED": "Jeddah, Saudi Arabia",
  "JIB": "Djibouti City, Djibouti",
  "JNB": "Johannesburg, South Africa",
  "JOG": "Yogyakarta, Indonesia",
  "JOI": "Joinville, Brazil",
  "JRG": "Sambalpur, India",
  "JXG": "Jiaxing, China",
  "KBP": "Kyiv, Ukraine",
  "KCH": "Kuching, Malaysia",
  "KEF": "Reykjavík, Iceland",
  "KGL": "Kigali, Rwanda",
  "KHH": "Kaohsiung City",
  "KHI": "Karachi, Pakistan",
  "KHN": "Xinyu, China",
  "KIN": "Kingston, Jamaica",
  "KIV": "Chișinău, Moldova",
  "KIX": "Osaka, Japan",
  "KJA": "Krasnoyarsk, Russia",
  "KMG": "Kunming, China",
  "KNU": "Kanpur, India",
  "KTM": "Kathmandu, Nepal",
  "KUL": "Kuala Lumpur, Malaysia",
  "KWE": "Guiyang, China",
  "KWI": "Kuwait City, Kuwait",
  "LAD": "Luanda, Angola",
  "LAS": "Las Vegas, NV, United States",
  "LAX": "Los Angeles, CA, United States",
  "LCA": "Nicosia, Cyprus",
  "LED": "Saint Petersburg, Russia",
  "LHE": "Lahore, Pakistan",
  "LHR": "London, United Kingdom",
  "LIM": "Lima, Peru",
  "LIS": "Lisbon, Portugal",
  "LJU": "Ljubljana, Slovenia",
  "LLK": "Astara, Azerbaijan",
  "LLW": "Lilongwe, Malawi",
  "LOS": "Lagos, Nigeria",
  "LPB": "La Paz, Bolivia",
  "LUN": "Lusaka, Zambia",
  "LUX": "Luxembourg City, Luxembourg",
  "LYA": "Luoyang, China",
  "LYS": "Lyon, France",
  "MAA": "Chennai, India",
  "MAD": "Madrid, Spain",
  "MAN": "Manchester, United Kingdom",
  "MAO": "Manaus, Brazil",
  "MBA": "Mombasa, Kenya",
  "MCI": "Kansas City, MO, United States",
  "MCT": "Muscat, Oman",
  "MDE": "Medellín, Colombia",
  "MEL": "Melbourne, VIC, Australia",
  "MEM": "Memphis, TN, United States",
  "MEX": "Mexico City, Mexico",
  "MFM": "Macau",
  "MIA": "Miami, FL, United States",
  "MLA": "Santa Venera, Malta",
  "MLE": "Malé, Maldives",
  "MLG": "Malang, Indonesia",
  "MNL": "Manila, Philippines",
  "MPM": "Maputo, Mozambique",
  "MRS": "Marseille, France",
  "MRU": "Port Louis, Mauritius",
  "MSP": "Minneapolis, MN, United States",
  "MSQ": "Minsk, Belarus",
  "MUC": "Munich, Germany",
  "MXP": "Milan, Italy",
  "NAG": "Nagpur, India",
  "NBO": "Nairobi, Kenya",
  "NJF": "Najaf, Iraq",
  "NOU": "Noumea, New Caledonia",
  "NQN": "Neuquén, Argentina",
  "NQZ": "Astana, Kazakhstan",
  "NRT": "Tokyo, Japan",
  "NVT": "Timbó, Brazil",
  "OKA": "Naha, Japan ",
  "OKC": "Oklahoma City, OK, United States",
  "OMA": "Omaha, NE, United States",
  "ORD": "Chicago, IL, United States",
  "ORF": "Norfolk, VA, United States",
  "ORN": "Oran, Algeria",
  "OSL": "Oslo, Norway",
  "OTP": "Bucharest, Romania",
  "OUA": "Ouagadougou, Burkina Faso  ",
  "PAT": "Patna, India",
  "PBH": "Thimphu, Bhutan",
  "PBM": "Paramaribo, Suriname",
  "PDX": "Portland, OR, United States",
  "PER": "Perth, WA, Australia",
  "PHL": "Philadelphia, United States",
  "PHX": "Phoenix, AZ, United States",
  "PIT": "Pittsburgh, PA, United States",
  "PKX": "Langfang, China",
  "PMO": "Palermo, Italy",
  "PMW": "Palmas, Brazil",
  "PNH": "Phnom Penh, Cambodia",
  "PNQ": "Pune, India",
  "POA": "Porto Alegre, Brazil",
  "POS": "Port of Spain, Trinidad and Tobago",
  "PPT": "Tahiti, French Polynesia",
  "PRG": "Prague, Czech Republic",
  "PTY": "Panama City, Panama",
  "QRO": "Queretaro, MX, Mexico",
  "QWJ": "Americana, Brazil",
  "RAO": "Ribeirao Preto, Brazil",
  "RDU": "Durham, NC, United States",
  "REC": "Recife, Brazil",
  "RIC": "Richmond, VA, United States",
  "RIX": "Riga, Latvia",
  "RUH": "Riyadh, Saudi Arabia",
  "RUN": "Saint-Denis, Réunion",
  "SAN": "San Diego, CA, United States",
  "SAP": "San Pedro Sula, Honduras",
  "SAT": "San Antonio, TX, United States",
  "SCL": "Santiago, Chile",
  "SDQ": "Santo Domingo, Dominican Republic",
  "SEA": "Seattle, WA, United States",
  "SFO": "San Francisco, CA, United States",
  "SGN": "Ho Chi Minh City, Vietnam",
  "SHA": "Shanghai, China",
  "SIN": "Singapore, Singapore",
  "SJC": "San Jose, CA, United States",
  "SJK": "São José dos Campos, Brazil",
  "SJO": "San José, Costa Rica",
  "SJP": "São José do Rio Preto, Brazil",
  "SJU": "San Juan, Puerto Rico",
  // Cloudflare's status API labels SJW as Hengshui, although IATA assigns
  // SJW to Shijiazhuang Zhengding International Airport. Prefer Cloudflare's
  // own colo label here: the code alone does not establish the facility city.
  "SJW": "Hengshui, China",
  "SKG": "Thessaloniki, Greece",
  "SKP": "Skopje, North Macedonia",
  "SLC": "Salt Lake City, UT, United States",
  "SMF": "Sacramento, CA, United States",
  "SOD": "Sorocaba, Brazil",
  "SOF": "Sofia, Bulgaria",
  "SSA": "Salvador, Brazil",
  "STI": "Santiago de los Caballeros, Dominican Republic",
  "STL": "St. Louis, MO, United States",
  "STR": "Stuttgart, Germany  ",
  "SUV": "Suva, Fiji",
  "SYD": "Sydney, NSW, Australia",
  "SZX": "Shenzhen, China",
  "TAO": "Qingdao, China",
  "TBS": "Tbilisi, Georgia",
  "TEN": "Tongren, China",
  "TGU": "Tegucigalpa, Honduras",
  "TIA": "Tirana, Albania",
  "TLH": "Tallahassee, FL, United States",
  "TLL": "Tallinn, Estonia",
  "TLV": "Tel Aviv, Israel",
  "TNA": "Jinan, China",
  "TNR": "Antananarivo, Madagascar",
  "TPA": "Tampa, FL, United States",
  "TPE": "Taipei",
  "TUN": "Tunis, Tunisia",
  "TXL": "Berlin, Germany",
  "TYN": "Yangquan, China",
  "UDI": "Uberlândia, Brazil",
  "UIO": "Quito, Ecuador",
  "ULN": "Ulaanbaatar, Mongolia",
  "URT": "Surat Thani, Thailand",
  "VCP": "Campinas, Brazil",
  "VIE": "Vienna, Austria",
  "VIX": "Vitoria, Brazil",
  "VNO": "Vilnius, Lithuania",
  "VTE": "Vientiane, Laos",
  "WAW": "Warsaw, Poland",
  "WDH": "Windhoek, Namibia",
  "WLG": "Wellington, New Zealand",
  "WRO": "Wroclaw, Poland",
  "XAP": "Chapeco, Brazil",
  "XFN": "Xiangyang, China",
  "XIY": "Baoji, China",
  "XNH": "Nasiriyah, Iraq",
  "YHZ": "Halifax, Canada",
  "YUL": "Montréal, QC, Canada",
  "YVR": "Vancouver, BC, Canada",
  "YWG": "Winnipeg, MB, Canada",
  "YXE": "Saskatoon, SK, Canada",
  "YYC": "Calgary, AB, Canada",
  "YYZ": "Toronto, ON, Canada",
  "ZAG": "Zagreb, Croatia",
  "ZDM": "Ramallah",
  "ZRH": "Zurich, Switzerland",
};

export function formatCloudflareColo(code: string): string {
  return code
    .trim()
    .toUpperCase()
    .split("-")
    .map((part) => {
      const name = cloudflareColoNames[part];
      return name ? `${name} (${part})` : part;
    })
    .join(" / ");
}
